#### Importing Libraries

In [22]:
import pandas as pd

In [23]:
df=pd.read_csv('RISKS.csv')

In [24]:
df.head(10)

,Chain,Chain ID,Number of facilities,Number of states and territories with operations,Number of Special Focus Facilities (SFF),Number of SFF candidates,Number of facilities with an abuse icon,Percentage of facilities with an abuse icon,Percent of facilities classified as for-profit,Percent of facilities classified as non-profit,...,Average percentage of long-stay residents whose ability to move independently worsened,Average percentage of long-stay residents whose need for help with activities of daily living has increased,Average percentage of long-stay residents who were assessed and appropriately given the seasonal influenza vaccine,Average percentage of long-stay residents who were assessed and appropriately given the pneumococcal vaccine,Average percentage of long-stay residents who were physically restrained,Average percentage of long-stay residents with new or worsened bowel or bladder incontinence,Average percentage of long-stay residents who lose too much weight,Average percentage of long-stay residents who have symptoms of depression,Average percentage of long-stay residents who used antianxiety or hypnotic medication,Average rate of potentially preventable hospital readmissions 30 days after discharge from a SNF
0,National,NaN,14727,53,87,440,1463,9.9,73.7,19.8,...,16.5,14.9,95.4,93.4,0.1,19.8,5.4,11.3,19.6,10.8
1,603 HEALTHCARE,826.0,7,2,1,0,0,0.0,100.0,0.0,...,17.5,20.2,96.8,98.1,0.1,22.4,4.8,24.7,19.8,10.9
2,"ABBY GL, LLC",1.0,6,1,0,0,2,33.3,100.0,0.0,...,6.6,5.7,100.0,100.0,0.1,4.2,3.1,7.4,17.0,11.1
3,ABRAHAM BAK & MENACHEM GASTWIRTH,4.0,16,1,0,0,2,12.5,100.0,0.0,...,9.4,13.4,99.6,99.8,0.0,10.8,4.2,20.6,15.4,11.1
4,ABRAHAM SMILOW,808.0,7,1,0,0,2,28.6,100.0,0.0,...,27.4,24.6,79.2,80.5,0.0,26.7,7.7,8.7,21.9,11.0
5,ABSOLUT CARE,6.0,5,1,0,0,0,0.0,100.0,0.0,...,13.6,14.6,92.8,94.6,0.0,18.5,5.6,3.8,22.5,11.0
6,ACCELA HEALTHCARE,733.0,4,2,0,1,1,25.0,100.0,0.0,...,8.7,10.3,82.4,70.7,0.0,21.6,5.4,18.3,17.8,10.3
7,ACCOLADE HEALTHCARE,7.0,6,1,0,0,2,33.3,100.0,0.0,...,17.5,16.4,95.4,97.0,0.0,24.3,9.6,41.5,17.1,11.7
8,ACCURA HEALTHCARE,8.0,37,4,0,0,3,8.1,100.0,0.0,...,22.5,21.4,95.8,90.2,0.0,27.8,6.0,4.0,21.2,10.5
9,ACTS RETIREMENT-LIFE COMMUNITIES,9.0,26,9,0,0,1,3.8,0.0,100.0,...,14.4,16.0,97.7,95.8,0.0,20.2,4.6,0.2,17.7,11.3

##### Removing first row

In [25]:
df = df[df["Chain"] != "National"]

#### Removing unwanted columns

In [26]:
df.drop(columns=
        ['Chain', 'Chain ID', 'Number of states and territories with operations',
    'Number of Special Focus Facilities (SFF)', 'Number of SFF candidates',
    'Number of facilities with an abuse icon', 'Percentage of facilities with an abuse icon',
    'Percent of facilities classified as for-profit', 'Percent of facilities classified as non-profit',
    'Percent of facilities classified as government-owned', 'Average total weekend nurse hours per resident day',
    'Average Registered Nurse turnover percentage', 'Average number of administrators who have left the nursing home',
    'Average number of fines', 'Total amount of fines in dollars', 'Average amount of fines in dollars',
    'Average number of payment denials', 'Average percentage of short-stay residents who were re-hospitalized after a nursing home admission',
    'Average percentage of short-stay residents who have had an outpatient emergency department visit',
    'Average percentage of short-stay residents who newly received an antipsychotic medication',
    'Average percentage of short-stay residents with pressure ulcers or pressure injuries that are new or worsened',
    'Average percentage of short-stay residents who are at or above an expected ability to care for themselves and move around at discharge ',
    'Average percentage of short-stay residents who were assessed and appropriately given the seasonal influenza vaccine',
    'Average percentage of short-stay residents who were assessed and appropriately given the  pneumococcal vaccine',
    'Average number of outpatient emergency department visits per 1,000 long-stay resident days',
    'Average percentage of long-stay residents who received an antipsychotic medication',
    'Average percentage of long-stay residents who were assessed and appropriately given the seasonal influenza vaccine',
    'Average percentage of long-stay residents who were assessed and appropriately given the  pneumococcal vaccine',
    'Average percentage of long-stay residents who used antianxiety or hypnotic medication',
    'Average rate of potentially preventable hospital readmissions 30 days after discharge from a SNF'], inplace=True)

In [28]:
df.columns.tolist()

['Number of facilities',
 'Average overall 5-star rating',
 'Average health inspection rating',
 'Average staffing rating',
 'Average quality rating',
 'Average total nurse hours per resident day',
 'Average total Registered Nurse hours per resident day',
 'Average total nursing staff turnover percentage',
 'Total number of fines',
 'Total number of payment denials',
 'Average number of hospitalizations per 1,000 long-stay resident days',
 'Average percentage of long-stay residents experiencing one or more falls with major injury',
 'Average percentage of long-stay residents with pressure ulcers',
 'Average percentage of long-stay residents with a urinary tract infection',
 'Average percentage of long-stay residents who have or had a catheter inserted and left in their bladder',
 'Average percentage of long-stay residents whose ability to move independently worsened',
 'Average percentage of long-stay residents whose need for help with activities of daily living has increased',
 'Average percentage of long-stay residents who were physically restrained',
 'Average percentage of long-stay residents with new or worsened bowel or bladder incontinence',
 'Average percentage of long-stay residents who lose too much weight',
 'Average percentage of long-stay residents who have symptoms of depression']

#### Renaming Columns

In [29]:
df.rename(columns={
    'Number of facilities': 'num_facilities',
    'Average overall 5-star rating': 'overall_rating',
    'Average health inspection rating': 'health_rating',
    'Average staffing rating': 'staffing_rating',
    'Average quality rating': 'quality_rating',
    'Average total nurse hours per resident day': 'nurse_hours_total',
    'Average total Registered Nurse hours per resident day': 'rn_hours_total',
    'Average total nursing staff turnover percentage': 'staff_turnover_pct',
    'Total number of fines': 'total_fines',
    'Total number of payment denials': 'total_payment_denials',
    'Average number of hospitalizations per 1,000 long-stay resident days': 'hosp_per_1000_residents',
    'Average percentage of long-stay residents experiencing one or more falls with major injury': 'falls_with_injury',
    'Average percentage of long-stay residents with pressure ulcers': 'pressure_ulcers',
    'Average percentage of long-stay residents with a urinary tract infection': 'uti_pct',
    'Average percentage of long-stay residents who have or had a catheter inserted and left in their bladder': 'catheter_pct',
    'Average percentage of long-stay residents whose ability to move independently worsened': 'mobility_decline_pct',
    'Average percentage of long-stay residents whose need for help with activities of daily living has increased': 'adl_increase_pct',
    'Average percentage of long-stay residents who were physically restrained': 'restrained_pct',
    'Average percentage of long-stay residents with new or worsened bowel or bladder incontinence': 'incontinence_pct',
    'Average percentage of long-stay residents who lose too much weight': 'weight_loss_pct',
    'Average percentage of long-stay residents who have symptoms of depression': 'depression_pct'
}, inplace=True)

In [30]:
df.head()

,num_facilities,overall_rating,health_rating,staffing_rating,quality_rating,nurse_hours_total,rn_hours_total,staff_turnover_pct,total_fines,total_payment_denials,...,falls_with_injury,pressure_ulcers,uti_pct,catheter_pct,mobility_decline_pct,adl_increase_pct,restrained_pct,incontinence_pct,weight_loss_pct,depression_pct
1,7,2.2,2.7,1.8,2.0,3.4,0.7,51.4,5,0,...,4.7,5.1,2.8,2.1,17.5,20.2,0.1,22.4,4.8,24.7
2,6,2.3,2.2,3.7,4.2,4.3,0.5,34.8,5,6,...,1.6,3.9,0.1,0.0,6.6,5.7,0.1,4.2,3.1,7.4
3,16,2.5,2.4,3.1,3.3,4.6,0.5,34.5,14,3,...,1.6,5.7,1.3,0.6,9.4,13.4,0.0,10.8,4.2,20.6
4,7,1.3,1.7,2.4,2.9,3.3,0.5,49.5,6,0,...,2.7,5.6,2.0,1.6,27.4,24.6,0.0,26.7,7.7,8.7
5,5,3.6,3.6,2.8,3.8,3.5,0.4,47.8,0,0,...,3.6,4.1,0.9,0.3,13.6,14.6,0.0,18.5,5.6,3.8

In [31]:
df.to_csv("cleaned_data.csv", index=False)